# 开发环境配置覆盖
# 自动应用于 docker-compose up 命令

version: '3.8'

services:
  backend:
    build:
      target: production  # 开发环境也使用生产构建优化
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - RELOAD=true
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    volumes:
      - ./backend:/app:ro  # 只读挂载，提高安全性
      - backend_data_dev:/app/data
    ports:
      - "8080:8080"  # 暴露后端端口用于调试

  frontend:
    build:
      target: development  # 开发环境使用开发构建
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8080/api/v1
    volumes:
      - ./frontend:/app:ro  # 只读挂载
      - /app/node_modules  # 避免本地node_modules覆盖
    ports:
      - "5173:5173"  # Vite开发服务器

volumes:
  backend_data_dev:
    driver: local 